name: Release

on:
  workflow_dispatch:
    inputs:
      tests_succeeded:
        required: true
        type: boolean
        description: 'This input returns `true` if the tests are succeeded.'

jobs:
  release:
    if: ${{ inputs.tests_succeeded == true }}
    name: Run semanti release
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: Debug Workflow Run
        run: |
          echo "Workflow ${{ github.workflow }}"
          echo "Run Unit Tests Job: ${{ github.job }}"
          echo "Workflow Run Ref: ${{ github.ref }}"

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release
