name: Release

on:
  workflow_run:
    workflows: [Run e2e tests]
    types:
      - completed
    branches:
      - alpha

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success'
    name: Run semanti release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release
